# Generated by Django 2.1.7 on 2019-04-07 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.TimeField()),
                ('departure', models.TimeField(null=True)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NoFlightDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Days', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=10, null=True)),
                ('fk_flights', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline3app.FlightDetail')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('SSN', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('passenger_firstname', models.CharField(max_length=100)),
                ('passenger_lastname', models.CharField(max_length=100)),
                ('passenger_dob', models.DateField()),
                ('passenger_gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], default='female', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='PassengerTicketRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('flight_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_no', models.AutoField(primary_key=True, serialize=False)),
                ('route_dest', models.CharField(max_length=100)),
                ('route_src', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('JDate', models.DateField()),
                ('PNR', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Date_of_booking', models.DateField()),
                ('fk_flights', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline3app.FlightDetail')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('route_dest', 'route_src')},
        ),
        migrations.AddField(
            model_name='passengerticketrel',
            name='PNR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline3app.Ticket'),
        ),
        migrations.AddField(
            model_name='passengerticketrel',
            name='SSN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline3app.Passenger'),
        ),
        migrations.AddField(
            model_name='flightdetail',
            name='flight_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline3app.Plane'),
        ),
        migrations.AddField(
            model_name='flightdetail',
            name='route_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline3app.Route'),
        ),
        migrations.AlterUniqueTogether(
            name='passengerticketrel',
            unique_together={('PNR', 'SSN')},
        ),
        migrations.AlterUniqueTogether(
            name='flightdetail',
            unique_together={('flight_code', 'route_no')},
        ),
    ]
