# Generated by Django 2.2.1 on 2019-12-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline3app', '0002_auto_20191229_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightdetail',
            name='bus_route',
            field=models.PositiveIntegerField(default=4),
            preserve_default=False,
        ),
    ]
