# Generated by Django 2.2.1 on 2020-01-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline3app', '0004_auto_20191229_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightdetail',
            name='seats_available',
            field=models.PositiveIntegerField(default=200),
            preserve_default=False,
        ),
    ]
